### ISSUE TITLE
Test PSNR/SSIM value is small

### ISSUE THREAD

**Issue by ModestTony** [wdmwhh/C2M_RAB-CIFT-RTRR#1]
First of all, thank you very much for your work！
But I have some problems with my test code and would like to ask for some advice.
Using the open source code you provided as well as the trained pth file, but the result of my test PSNR/SSIM = 28.63/0.851 is quite different from the PSNR/SSIM = 28.83/0.856 in the paper. Also I found that the PSNR/SSIM = 28.63/0.851 of my test is the same as the PSNR/SSIM of Baseline+PFA in the ablation part of your paper 4.4 Ablation Study Table 2. Is it possible that you have put the wrong trained pth file.
![image](https://user-images.githubusercontent.com/56422026/233820494-acc77103-d3d4-4378-87dc-79668299b462.png)

**Comment by wdmwhh** [comment]
I'm sorry for late replies. Using the test code, it is supposed to output two results (one for single ref and multiple refs that is stitched to the whole image):
Validation CUFED5 # PSNR: 2.6836e+01 # PSNR_Y: 2.8636e+01 # SSIM_Y: 8.5052e-01.
Validation CUFED5 # PSNR: 2.7016e+01 # PSNR_Y: 2.8831e+01 # SSIM_Y: 8.5616e-01.
The paper reports the PSNR_Y of the latter.
And thus, PSNR/SSIM = 28.63/0.851 of your test may be the PSNR_Y of the former.
